[theme]
# Основной цвет для активных элементов (обводка при клике, кнопки, радио-кнопки)
primaryColor = "#FF6B00"

# Цвет фона самого приложения (светлый)
backgroundColor = "#FFFFFF"

# Цвет фона для боковой панели (sidebar)
secondaryBackgroundColor = "#F8F9FA"

# Цвет основного текста
textColor = "#31333F"